; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:teensy41]
platform  = teensy
board     = teensy41
framework = arduino

; Activa USB MIDI+Serial (equivalente a Tools → USB Type → "Serial + MIDI" en el IDE)
; Sin este flag, el objeto usbMIDI no existe y el compilador lo rechaza.
build_flags = -D USB_MIDI_SERIAL

lib_deps =
    olikraus/U8g2
    https://github.com/FortySevenEffects/arduino_midi_library.git
    paulstoffregen/Encoder
    bblanchon/ArduinoJson @ ^7.0.0

monitor_speed = 115200
monitor_dtr   = 1
monitor_rts   = 1

; FUERZA EL PUERTO CORRECTO (puede ser ttyACM0 o ttyACM1)
monitor_port = /dev/ttyACM0